# Generated by Django 4.2.18 on 2025-04-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptfile',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
